# Generated by Django 5.0 on 2024-03-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='full name'),
        ),
    ]
