# Generated by Django 5.0 on 2024-03-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0004_alter_ticket_sender_email_alter_ticket_sender_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['-sent_at'], 'verbose_name': 'ticket message', 'verbose_name_plural': 'ticket messages'},
        ),
    ]
