# Generated by Django 5.0 on 2024-03-22 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0006_ticketmessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer_support.ticket', verbose_name='ticket'),
        ),
    ]
