# Generated by Django 5.0 on 2024-03-27 07:21

import customer_support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0007_alter_ticketmessage_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='access_key',
            field=models.CharField(default=customer_support.models.get_access_key, max_length=42, verbose_name='access key'),
        ),
    ]
