# Generated by Django 5.0 on 2024-02-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_video_hash',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='YouTube video hash'),
        ),
    ]
