# Generated by Django 5.0 on 2024-02-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_project_youtube_video_hash_projectlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlike',
            name='like_type',
            field=models.IntegerField(choices=[(0, '&#x2764;&#xfe0f;'), (1, '&#128163;'), (2, '&#128293;'), (3, '&#128077;'), (4, '&#128405;'), (5, '&#128078;')], default=3, verbose_name='type'),
        ),
    ]
